name: flutter_from_builder_package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Flutter Form Builder Package
  flutter_form_builder: ^7.7.0
  # Form Builder Validator Package
  form_builder_validators: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true